package BAB1;

public class PerpustakaanTest {

    public static void main(String[] args) {
        Perpustakaan tek1 = new Perpustakaan();
        tek1.setPerpus("Teknologi", "Merajut jejaring teknologi informatika, komunikasi, dan media massa", "Arifianto, S.", "");
        Perpustakaan tek2 = new Perpustakaan();
        tek2.setPerpus("Teknologi", "Teknologi informasi perpustakaan = strategi perancangan perpustakaan digital", "Muhsin,Ahmad", "");
        Perpustakaan tek3 = new Perpustakaan();
        tek3.setPerpus("Teknologi", "Sistem dan teknologi informasi", "Effendi, Usman", "");
        Perpustakaan tek4 = new Perpustakaan();
        tek4.setPerpus("Teknologi", "Buku pintar Linux = open source Linux, membangun kekuatan baru teknologi informasi dunia", "Indraji, Ardiansyah", "");
        Perpustakaan tek5 = new Perpustakaan();
        tek5.setPerpus("Teknologi", "Sistem Teknologi Informasi, Pendekatan terintegrasi = Konsep dasar, teknologi, aplikasi, pengembangan dan pengelolaan", "Hartono, Jogiyanto", "");
        Perpustakaan fil1 = new Perpustakaan();
        fil1.setPerpus("Filsafat", "Filsafat ilmu lanjutan", "Rahmat, Aceng", "Akhadiah, Sabarti");
        Perpustakaan fil2 = new Perpustakaan();
        fil2.setPerpus("Filsafat", "Filsafat Pendidikan", "Suhartono, Suparlan", "Muhsin, llyya");
        Perpustakaan fil3 = new Perpustakaan();
        fil3.setPerpus("Filsafat", "Filsafat Hukum Perdata dalam tanya jawab", "Halim,A. Ridwan", "");
        Perpustakaan fil4 = new Perpustakaan();
        fil4.setPerpus("Filsafat", "Pengantar filsafat pendidikan islam", "Marimba, Ahmad D.", "");
        Perpustakaan fil5 = new Perpustakaan();
        fil5.setPerpus("Filsafat", "Sosiologi dan filsafat", "Durkheim, Emile", "");
        Perpustakaan sej1 = new Perpustakaan();
        sej1.setPerpus("Sejarah", "Sejarah pergerakan rakyat Indonesia", "Pringgodigdo,A.K.", "");
        Perpustakaan sej2 = new Perpustakaan();
        sej2.setPerpus("Sejarah", "Lintas Sejarah Imigrasi Indonesia", "Ramadhan K.H.", "");
        Perpustakaan sej3 = new Perpustakaan();
        sej3.setPerpus("Sejarah", "Sejarah perkembangan ilmu ekonomi", "Winardi", "");
        Perpustakaan sej4 = new Perpustakaan();
        sej4.setPerpus("Sejarah", "Pengantar sejarah perekonomian dunia = akhir abad pertengahan sampai perang dunia II", "Harjosubroto, Sudinar", "");
        Perpustakaan sej5 = new Perpustakaan();
        sej5.setPerpus("Sejarah", "Teori komunikasi = sejarah, metode dan terapan dalam media massa", "Severin, Werner J.", "Tankard, James W., Jr");
        Perpustakaan ag1 = new Perpustakaan();
        ag1.setPerpus("Agama", "Agama dan perubhan sosiopolitik", "Esposito, John L.", "");
        Perpustakaan ag2 = new Perpustakaan();
        ag2.setPerpus("Agama", "Islam Akomodatif = Rekonstruksi pemahaman Islam sebagai Agama Universal", "Yasid, Abu", "");
        Perpustakaan ag3 = new Perpustakaan();
        ag3.setPerpus("Agama", "Metode penelitian agama = suatu pengantar", "Abdullah, Taufik", "Karim, M. Rusli");
        Perpustakaan ag4 = new Perpustakaan();
        ag4.setPerpus("Agama", "Al-Qur'an dan pluralisme agama", "Qaramaliki, Muhammad Hasan Qadrdan", "");
        Perpustakaan ag5 = new Perpustakaan();
        ag5.setPerpus("Agama", "Nasihat-nasihat agama Islam", "Haddad, Abdulloh Ba'Alawi Al.", "");
        Perpustakaan psik1 = new Perpustakaan();
        psik1.setPerpus("Psikologi", "Kamus lengkap psikologi", "Chaplin, J. P.", "Kartono, Kartini");
        Perpustakaan psik2 = new Perpustakaan();
        psik2.setPerpus("Psikologi", "Psikologi Pendidikan", "Martaniah, Sri Mulyani", "");
        Perpustakaan psik3 = new Perpustakaan();
        psik3.setPerpus("Psikologi", "Psikologi abnormal", "Greene, Beverly", "");
        Perpustakaan psik4 = new Perpustakaan();
        psik4.setPerpus("Psikologi", "Psikologi kepribadian", "Hadi, Taufik", "");
        Perpustakaan psik5 = new Perpustakaan();
        psik5.setPerpus("Psikologi", "Psikologi sosial", "Clayton, Debbie", "");
        Perpustakaan pol1 = new Perpustakaan();
        pol1.setPerpus("Politik", "Analisa politik modern", "Dahl, Robert A.", "");
        Perpustakaan pol2 = new Perpustakaan();
        pol2.setPerpus("Politik", "Konsesus politik nasional orde baru = ortodoksi dan aktualisasinya", "Silalahi, Harry Tjan", "");
        Perpustakaan pol3 = new Perpustakaan();
        pol3.setPerpus("Politik", "Perbandingan sistem politik", "MacAndrews, Colin", "Mas'ud, Mohtar");
        Perpustakaan pol4 = new Perpustakaan();
        pol4.setPerpus("Politik", "Pengantar teori politik ekonomi", "Winardi", "");
        Perpustakaan pol5 = new Perpustakaan();
        pol5.setPerpus("Politik", "Hukum, politik dan perubahan sosial", "Kusumah, Mulyana W.", "");
        Perpustakaan fik1 = new Perpustakaan();
        fik1.setPerpus("Fiksi", "Melbourne(Rewind)", "Efendi, Winna", "");
        Perpustakaan fik2 = new Perpustakaan();
        fik2.setPerpus("Fiksi", "Manusia Setengah Salmon", "Dika, Raditya", "");
        Perpustakaan fik3 = new Perpustakaan();
        fik3.setPerpus("Fiksi", "Pillow Talk", "Simamora, Christian", "");
        Perpustakaan fik4 = new Perpustakaan();
        fik4.setPerpus("Fiksi", "Malam Tanpa Akhir", "Manis, Hoeda", "");
        Perpustakaan fik5 = new Perpustakaan();
        fik5.setPerpus("Fiksi", "99 Cahaya di langit Eropa", "Rais, Hanum Salsabiela", "");

        tek1.getPerpus();
        tek2.getPerpus();
        tek3.getPerpus();
        tek4.getPerpus();
        tek5.getPerpus();
        System.out.println("==================================================================================================================================");
        fil1.getPerpus();
        fil2.getPerpus();
        fil3.getPerpus();
        fil4.getPerpus();
        fil5.getPerpus();
        System.out.println("==================================================================================================================================");
        sej1.getPerpus();
        sej2.getPerpus();
        sej3.getPerpus();
        sej4.getPerpus();
        sej5.getPerpus();
        System.out.println("==================================================================================================================================");
        ag1.getPerpus();
        ag2.getPerpus();
        ag3.getPerpus();
        ag4.getPerpus();
        ag5.getPerpus();
        System.out.println("==================================================================================================================================");
        psik1.getPerpus();
        psik2.getPerpus();
        psik3.getPerpus();
        psik4.getPerpus();
        psik5.getPerpus();
        System.out.println("==================================================================================================================================");
        pol1.getPerpus();
        pol2.getPerpus();
        pol3.getPerpus();
        pol4.getPerpus();
        pol5.getPerpus();
        System.out.println("==================================================================================================================================");
        fik1.getPerpus();
        fik2.getPerpus();
        fik3.getPerpus();
        fik4.getPerpus();
        fik5.getPerpus();
    }
}